# Plot Cecal osmolalities

# 1. Load libraries
```{r}
library(tidyverse)
library(readxl)
library(ggsci)
```

# 2. load the data
```{r}
osmo <- read_excel(path = "Cecal_osmolalities.xlsx") %>%
  mutate(Treatment_PEG = paste0(Treatment_PEG, "% PEG")) %>%
  mutate(Bacteria = if_else(Bacteria == "C. boltea", "C. bolteae","C. clostridioforme 538"))
osmo
```

```{r}
osmo %>% 
  ggplot(aes(x = Bacteria, y = Osmolality, fill = Treatment_PEG)) +
    geom_boxplot(alpha = 0.5) +
    geom_point(position=position_jitterdodge(jitter.width = 0.2), alpha = 0.6) +
    scale_y_continuous(limits = c(0, 900),n.breaks = 9, expand = c(0, 0)) +
    theme_light() +
    scale_fill_aaas() +
    labs(x = "Strain", y = "Osmolality (mOsm/kg)", fill = "PEG in water (w/v)") +
  theme(panel.border = element_rect(color = "black"),
        panel.grid = element_line(colour = "grey96"),
        axis.ticks = element_line(color = "black"),
        #strip.text.x = element_text(size=12, face="italic", color = "black"),
        strip.text.x = element_blank(),
        axis.title = element_text(size = 12),
        axis.text.x =element_text(size=16, face = "italic"),
        axis.text.y = element_text(size=16),
        legend.position = c(0.75, 0.2)
        )

```

# 4. Stats for osmo

Calculate significance for C. boltea using two sample t-test
```{r}
# filter dat
dat_bolt <- osmo %>%
  filter(Bacteria == "C. bolteae")
dat_bolt

# do barlett test to check for equal variance
bartlett.test(Osmolality~Treatment_PEG, data = dat_bolt) # use Var.equal = TRUE

# Perform two sample t test
t.test(Osmolality~Treatment_PEG, data = dat_bolt,
       var.equal = TRUE,
       conf.level = 0.95)

```


Calculate significance for C. boltea using two sample t-test
```{r}
# filter dat
dat_CF538 <- osmo %>%
  filter(Bacteria == "C. clostridioforme 538")
dat_CF538

# do barlett test to check for equal variance
bartlett.test(Osmolality~Treatment_PEG, data = dat_CF538) # use Var.equal = TRUE

# Perform two sample t test
t.test(Osmolality~Treatment_PEG, data = dat_CF538,
       var.equal = FALSE,
       conf.level = 0.95)

```



