# Analyze the compiled inovirus qPCR data

#1. load the libraries
```{r}
library(tidyverse)
library(ggsci)
library(readxl)
```

#2. load the data
```{r}
dat <- read_excel(path = "gDNA_dat_compiled.xlsx")
dat
```

#3. plot the data
```{r}
dat %>%
  ggplot(aes(x = Strain, y = mean_Copy_number_gDNA_g, fill = Treatment_PEG)) +
  geom_boxplot(alpha = 0.6) +
  geom_point(size =1.5, position=position_jitterdodge(jitter.width = .2)) +
  scale_y_log10(limits = c(1e+0, 1e+12), n.breaks = 12, expand = c(0, 0)) +
  scale_fill_npg() +
  theme_classic() +
  labs(x = "Strain", y = "Genome copy #/g of cecal contents", fill = "PEG in water (w/v)")+
  
  theme(strip.text.x = element_text(size=10, colour = "Black"),
      strip.background = element_rect(colour="black", fill="grey90"),
      axis.text.x = element_text(angle = 45,hjust=1, face = "italic")
      )
```

# 4 test for significance using t-test

Test for E. bolteae: Calculate significance using two sample t-test
```{r}
# filter dat
dat_bolt <- dat %>%
  filter(Strain == "E. bolteae")
dat_bolt

# do barlett test to check for equal variance
bartlett.test(mean_Copy_number_gDNA_g~Treatment_PEG, data = dat_bolt) # use Var.equal = TRUE

# Perform two sample t test
t.test(mean_Copy_number_gDNA_g~Treatment_PEG, data = dat_bolt,
       var.equal = TRUE,
       conf.level = 0.95)

```

Test for E. clostridioformis 538: Calculate significance using two sample t-test
```{r}
# filter dat
dat_CF538 <- dat %>%
  filter(Strain == "E. clostridioformis 538")
dat_CF538

# do barlett test to check for equal variance
bartlett.test(mean_Copy_number_gDNA_g~Treatment_PEG, data = dat_CF538) # use Var.equal = TRUE

# Perform two sample t test
t.test(mean_Copy_number_gDNA_g~Treatment_PEG, data = dat_CF538,
       var.equal = TRUE,
       conf.level = 0.95)

```
