# Analyze the compiled inovirus qPCR data

#1. load the libraries
```{r}
library(tidyverse)
library(ggsci)
library(readxl)
```

#2. load the data
```{r}
dat <- read_excel(path = "Norm_dat_compiled.xlsx") %>%
  mutate(Treatment_PEG = paste0(Treatment_PEG*100, "%"))
dat
```

#3. plot the data - Bolt
```{r}
dat %>%
  filter(Strain == "E. bolteae") %>%
  ggplot(aes(x = Treatment_PEG, y = Norm_copy_number, fill = Treatment_PEG)) +
  geom_boxplot(alpha = 0.4, aes(color = Treatment_PEG)) +
  geom_point(size =1.5) +
  scale_y_continuous(limits = c(0, 1200), n.breaks = 12, expand = c(0,0)) +
  scale_fill_aaas() +
  #scale_color_aaas() +
  theme_classic() +
  labs(x = "PEG in water (w/v)", y = "Inovirus copies/10^6 Genome copies", fill = "PEG in water (w/v)")
```
Calculate significance using two sample t-test
```{r}
# filter dat
dat_bolt <- dat %>%
  filter(Strain == "E. bolteae")
dat_bolt

# do barlett test to check for equal variance
bartlett.test(Norm_copy_number~Treatment_PEG, data = dat_bolt) # use Var.equal = TRUE

# Perform two sample t test
t.test(Norm_copy_number~Treatment_PEG, data = dat_bolt,
       var.equal = TRUE,
       conf.level = 0.95)

```



#3. plot the data - CF538
```{r}
dat %>%
  filter(Strain == "E. clostridioformis 538") %>%
  ggplot(aes(x = Treatment_PEG, y = Norm_copy_number, fill = Treatment_PEG)) +
  geom_boxplot(alpha = 0.4, aes(color = Treatment_PEG)) +
  geom_point(size =1.5) +
  scale_y_continuous(limits = c(0, 130000), n.breaks = 13, expand = c(0,0)) +
  scale_fill_jama() +
  #scale_color_jama() +
  theme_classic() +
  labs(x = "PEG in water (w/v)", y = "Inovirus copies/10^6 Genome copies", fill = "PEG in water (w/v)")
```
stats using two sample t-test
```{r}
# filter dat
dat_CF538 <- dat %>%
  filter(Strain == "E. clostridioformis 538")
dat_CF538

# do barlett test to check for equal variance
bartlett.test(Norm_copy_number~Treatment_PEG, data = dat_CF538) # use Var.equal = FALSE

# Perform two sample t test
t.test(Norm_copy_number~Treatment_PEG, data = dat_CF538,
       var.equal = FALSE,
       conf.level = 0.95)

```


# 4. plot the data based on the osmolality

First load the osmolality data
```{r}
osmo <- read_excel(path = "Cecal_osmolalities.xlsx") %>%
  rename(Strain = Bacteria) %>%
  rename(Sample = `Tube name`) %>%
  mutate(Treatment_PEG = paste0(Treatment_PEG, "%")) %>%
  select(Sample, Strain, Treatment_PEG, Osmolality)
osmo
```

Join the data
```{r}
dat_osmo <- dat %>%
  left_join(osmo)
dat_osmo
```

plot osmo data for E. boltea
```{r}
dat_osmo %>%
  filter(Strain == "E. bolteae") %>%
  ggplot(aes(x = Osmolality, y = Norm_copy_number, color = Treatment_PEG)) +
  geom_point(size =3) +
  scale_y_continuous(limits = c(0, 1200), n.breaks = 12, expand = c(0,0)) +
  scale_color_aaas() +
  theme_classic() +
  labs(x = "Osmolality", y = "Inovirus copies/10^6 Genome copies", color = "PEG in water (w/v)")
```


Plot data for E. clostridioformis 538
```{r}
dat_osmo %>%
  filter(Strain == "E. clostridioformis 538") %>%
  ggplot(aes(x = Osmolality, y = Norm_copy_number, color = Treatment_PEG)) +
  geom_point(size =3) +
  scale_y_continuous(limits = c(0, 130000), n.breaks = 13, expand = c(0,0)) +
  scale_color_jama() +
  theme_classic() +
  labs(x = "Osmolality", y = "Inovirus copies/10^6 Genome copies", color = "PEG in water (w/v)")
```

exgta plot
```{r}
p <- dat %>%
  filter(Strain == "E. bolteae") %>%
  ggplot(aes(x = Treatment_PEG, y = Norm_copy_number, fill = Treatment_PEG)) +
  geom_boxplot(alpha = 0.5) +
  geom_point(size =1.5, position=position_jitterdodge(jitter.width = 0.2)) +
  facet_wrap(.~Strain, scales = "free") +
  scale_y_continuous(limits = c(0, 1200),expand = c(0,0), n.breaks = 8) +
  scale_fill_aaas() +
  theme_light() +
  labs(x = "PEG in water (w/v)", y = "Inovirus copies/10^6 Genome copies", fill = "PEG in water (w/v)") +
    theme(panel.border = element_rect(color = "black"),
        panel.grid = element_line(colour = "grey96"),
        axis.ticks = element_line(color = "black"),
        #strip.text.x = element_text(size=12, face="italic", color = "black"),
        strip.text.x = element_blank(),
        axis.title = element_text(size = 12),
        axis.text.x =element_text(size=16),
        axis.text.y = element_text(size=16),
        legend.position = "none"
        )
p
```

clost
```{r}
p <- dat %>%
  filter(Strain == "E. clostridioformis 538") %>%
  ggplot(aes(x = Treatment_PEG, y = Norm_copy_number, fill = Treatment_PEG)) +
  geom_boxplot(alpha = 0.5) +
  geom_point(size =1.5, position=position_jitterdodge(jitter.width = 0.2)) +
  facet_wrap(.~Strain, scales = "free") +
  #scale_y_continuous(limits = c(0, 1200),expand = c(0,0), n.breaks = 12) +
  scale_y_continuous(limits = c(0, 140000), n.breaks = 7, expand = c(0,0)) +
  scale_fill_manual(values = c("#3B4992FF", "#008B45FF"))+
  theme_light() +
  labs(x = "PEG in water (w/v)", y = "Inovirus copies/10^6 Genome copies", fill = "PEG in water (w/v)") +
    theme(panel.border = element_rect(color = "black"),
        panel.grid = element_line(colour = "grey96"),
        axis.ticks = element_line(color = "black"),
        #strip.text.x = element_text(size=12, face="italic", color = "black"),
        strip.text.x = element_blank(),
        axis.title = element_text(size = 12),
        axis.text.x =element_text(size=16),
        axis.text.y = element_text(size=16),
        legend.position = "none"
        )
p
```





