---
title: "Untitled"
author: "Juan"
date: "13/01/2022"
output: html_document
---

load the libraries
```{r}
library(tidyverse)
library(ComplexHeatmap)
library(readxl)
library(circlize)
```


Load the data
```{r}
dat <- read_excel("ANIb_percentage_identity.xlsx")
dat


```

Make the complex heatmap
```{r}
dat_matrix <- as.matrix(dat[-1])
rownames(dat_matrix) <- dat %>% select(1) %>% pull

#dat_matrix
```

Make the heatmap
```{r}

f1 = colorRamp2(seq(min(dat_matrix), max(dat_matrix), length = 3), c("#EEEEEE", "lightsteelblue1", "dodgerblue3"))

Heatmap(dat_matrix, 
        col = f1,
        name = "% Identity",
        column_title = "Average Nucleotide Identity", 
        rect_gp = gpar(col = "grey80"),
        row_dend_side = "right",
        #border = T,
        cluster_rows = T,
        row_names_side = "left",
        row_names_gp = gpar(fontsize = 8, fontface = "italic"), # controls the font size of row names
        column_names_gp = gpar(fontsize = 8, fontface = "italic"),
        column_names_rot = 45,
        row_names_max_width = max_text_width(rownames(dat_matrix),gp = gpar(fontsize = 8)),
        column_names_max_height = max_text_width(rownames(dat_matrix)),
        
        
        #cell_fun = function(j, i, x, y, width, height, fill) {
        #grid.text(sprintf("%.2f", dat_matrix[i, j]), x, y, gp = gpar(fontsize = 14))}
        )


```


